### ISSUE TITLE
segfault when compiling on CentOS7

### ISSUE THREAD

**Issue by jstrube** [pnnl/tazer#21]
I've tried to compile on b2dcdev32, but without success.
I've checked out f36a1f1b458f6622586e9c0e918e8bf8a893252e, but neither compiling with gcc9.3.0 nor with gcc8.2.0 leads to a binary that I can execute.
gcc9.3.0 can be set up with this: `source /cvmfs/belle.cern.ch/tools/b2setup release-05-01-12`

gcc8.2.0 can be set up like this: `source /cvmfs/belle.cern.ch/tools/b2setup release-03-02-04`

In both cases, compiling succeeds, but trying to start the server fails. I'm setting the following envvars:
```
export LD_PRELOAD=/ext/home/jstrube/TAZeR_bin/lib/libclient.so
export TAZER_PRIVATE_MEM_CACHE_SIZE=$((1024*1024))
export TAZER_SHARED_MEM_CACHE=0
export TAZER_SHARED_MEM_CACHE_SIZE=$((1*1024*1024*1024))
export TAZER_BOUNDED_FILELOCK_CACHE=0
export TAZER_BOUNDED_FILELOCK_CACHE_SIZE=$((16*1024*1024*1024))
```

Setting `TAZER_SHARED_MEM_CACHE=1` and `TAZER_BOUNDED_FILELOCK_CACHE=1` does not help. Executing the server fails with 
```
[TAZER] Constructing privatememory in memory cache
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc./start_server.sh: line 7: 23327 Segmentation fault      /ext/home/jstrube/TAZeR_bin/bin/server
```
gdb gives this information:
```
(gdb) where
#0  0x00007f56054edd91 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007f56054cfed5 in fputs () from /lib64/libc.so.6
#2  0x00007f5606372edd in innerWrapper<int (*)(TazerFile*, unsigned int, int, int, _IO_FILE*), int (*)(int, _IO_FILE*), int, _IO_FILE*> (
    fp=0x7f56058291c0 <_IO_2_1_stderr_>, isTazerFile=@0x7ffce51764ef: false, tazerFun=0x7f56063688d6 <tazerFputc(TazerFile*, unsigned int, int, int, _IO_FILE*)>, 
    localFun=0x7f56054cfec0 <fputs>, args#0=10, args#1=0x7f56058291c0 <_IO_2_1_stderr_>) at /ext/home/jstrube/tazer/inc/tazer/client/Lib.h:247
#3  0x00007f5606372fcd in outerWrapper<_IO_FILE*, int (*)(TazerFile*, unsigned int, int, int, _IO_FILE*), int (*)(int, _IO_FILE*), int, _IO_FILE*> (
    name=0x7f56064922da "fputc", fileId=0x7f56058291c0 <_IO_2_1_stderr_>, metric=Timer::fputc, 
    tazerFun=0x7f56063688d6 <tazerFputc(TazerFile*, unsigned int, int, int, _IO_FILE*)>, posixFun=0x7f56054cfec0 <fputs>, args#0=10, 
    args#1=0x7f56058291c0 <_IO_2_1_stderr_>) at /ext/home/jstrube/tazer/inc/tazer/client/Lib.h:303
#4  0x00007f5606368955 in fputc (c=10, fp=0x7f56058291c0 <_IO_2_1_stderr_>) at /ext/home/jstrube/tazer/src/client/Lib.cpp:531
#5  0x00000000005e14a1 in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
#6  0x00000000007054c6 in __cxxabiv1::__terminate(void (*)()) ()
#7  0x0000000000705501 in std::terminate() ()
#8  0x0000000000705af4 in __cxa_throw ()
#9  0x000000000070462c in operator new(unsigned long) ()
#10 0x00000000006c5ef5 in MemoryCache::MemoryCache (this=0x26a9960, cacheName=..., type=privateMemory, cacheSize=21474836480, blockSize=1048576, associativity=16)
    at /ext/home/jstrube/tazer/src/caches/bounded/deprecated/MemoryCache.cpp:106
#11 0x00000000006c6a12 in MemoryCache::<lambda()>::operator()(void) const (__closure=0x26a9930) at /ext/home/jstrube/tazer/src/caches/bounded/deprecated/MemoryCache.cpp:238
#12 0x00000000006c6c55 in std::_Function_handler<Cache*(), MemoryCache::addNewMemoryCache(std::__cxx11::string, CacheType, uint64_t, uint64_t, uint32_t)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /cvmfs/belle.cern.ch/el7/externals/v01-07-01/include/c++/bits/std_function.h:282
#13 0x000000000065c758 in std::function<Cache* ()>::operator()() const (this=0x7ffce5176910)
    at /cvmfs/belle.cern.ch/el7/externals/v01-07-01/include/c++/bits/std_function.h:687
#14 0x000000000065b240 in Trackable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Cache*>::AddTrackable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<Cache* ()>, std::function<void (Cache*)>, bool&) (k=..., createNew=..., reuseOld=..., 
    created=@0x7ffce51768ef: false) at /ext/home/jstrube/tazer/inc/tazer/Trackable.h:111
#15 0x000000000065a1f8 in Trackable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Cache*>::AddTrackable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<Cache* ()>) (k=..., createNew=...) at /ext/home/jstrube/tazer/inc/tazer/Trackable.h:135
#16 0x00000000006c6b11 in MemoryCache::addNewMemoryCache (cacheName=..., type=privateMemory, cacheSize=21474836480, blockSize=1048576, associativity=16)
    at /ext/home/jstrube/tazer/src/caches/bounded/deprecated/MemoryCache.cpp:236
#17 0x00000000005e53f6 in ServeFile::cache_init () at /ext/home/jstrube/tazer/src/server/ServeFile.cpp:180
#18 0x00000000005e30be in main (argc=1, argv=0x7ffce5176d38) at /ext/home/jstrube/tazer/src/server/Server.cpp:286
```

**Comment by rdfriese** [comment]
Ahh this is likely a (lack of) documentation issue...
Try setting: TAZER_SERVER_CACHE_SIZE=$(100\*1024\*1024) 
or some smaller number, the default for the server is a 2GB cache which I think is larger than our VM

Technically you don't need to set LD_PRELOAD for the server, although it *shouldn't* cause any issues (and in fact this will be explicitly supported in the near future when we finalize composable servers)

**Comment by jstrube** [comment]
That does the trick!
